# Generated by Django 4.2.6 on 2024-10-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelstop',
            name='retail_price',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
